/*
 * This file was generated by the Gradle 'init' task.
 */
group = "io.github.wldt"
version = "0.3.0"
description = "The core library to build White Label Digital Twins"
java.sourceCompatibility = JavaVersion.VERSION_1_8

plugins {
    `java-library`
    `maven-publish`
    signing
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    api("org.apache.commons:commons-lang3:3.9")
    api("ch.qos.logback:logback-classic:1.4.12")
    api("javax.inject:javax.inject:1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.10.1")
}

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).addBooleanOption("html5", true)
    }
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            name = "Sonatype"
            val releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            val snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots"
            url = uri(if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl)
            credentials {
                username = (properties["ossrhUsername"] as String?)
                password = (properties["ossrhPassword"] as String?)
            }
        }
        maven {
            name = "Local"
            val releasesRepoUrl = layout.buildDirectory.dir("repos/releases")
            val snapshotsRepoUrl = layout.buildDirectory.dir("repos/snapshots")
            url = uri(if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl)
        }
    }
    publications.create<MavenPublication>("WLDTRelease") {
        from(components["java"])

        pom {
            name = "WLDT Core"
            url = "https://wldt.github.io/"
            description = project.description;
            licenses {
                license {
                    name = "Apache-2.0 license"
                    url = "https://raw.githubusercontent.com/wldt/wldt-core-java/master/LICENSE"
                }
            }

            developers {
                developer {
                    id = "samubura"
                    name = "Samuele Burattini"
                    email = "samuele.burattini@unibo.it"
                }
                developer {
                    id = "piconem"
                    name = "Marco Picone"
                    email = "picone.m@gmail.com"
                }
            }

            scm {
                connection = "scm:git:https://github.com/wldt/wldt-core-java.git"
                url = "https://github.com/wldt/wldt-core-java"
            }
        }
    }
}

signing {
    sign(publishing.publications["WLDTRelease"])
}
