package it.wldt.process.metrics;

import it.wldt.adapter.physical.event.PhysicalAssetEventWldtEvent;
import it.wldt.adapter.physical.event.PhysicalAssetPropertyWldtEvent;
import it.wldt.augmentation.function.AugmentationFunction;
import it.wldt.augmentation.result.AugmentationFunctionResult;
import it.wldt.core.state.DigitalTwinState;
import it.wldt.core.state.DigitalTwinStateEventNotification;
import it.wldt.log.WldtLogger;
import it.wldt.log.WldtLoggerProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Marco Picone, Ph.D. - picone.m@gmail.com
 * @project wldt-core
 * @created 28/12/2023 - 20:49
 */
public class SharedTestMetrics {

    private static final WldtLogger logger = WldtLoggerProvider.getLogger(SharedTestMetrics.class);

    private static SharedTestMetrics instance = null;

    // Physical Property Events generated by the Physical Adapter
    private Map<String, List<PhysicalAssetPropertyWldtEvent<?>>> physicalAdapterPropertyEventMap;

    // Physical Event Notification generated by the Physical Adapter
    private Map<String, List<PhysicalAssetEventWldtEvent<?>>> physicalAdapterEventNotificationMap;

    // Physical Property Events generated by the Twin through the Shadowing Function
    private Map<String, List<PhysicalAssetPropertyWldtEvent<?>>> shadowingFunctionPropertyEventMap;

    // Physical Property Events generated by the Twin through the Shadowing Function
    private Map<String, List<PhysicalAssetEventWldtEvent<?>>> shadowingFunctionEventNotificationMap;

    // DT Digital Events Notification generated by the Twin
    private Map<String, List<DigitalTwinStateEventNotification<?>>> digitalAdapterEventNotificationMap;

    // DT Digital State Update generated by the Twin
    private Map<String, List<DigitalTwinState>> digitalAdapterStateUpdateMap;

    // DT Resource Manager Notification Map
    private Map<String, List<String>> resourceManagerNotificationMap;

    // DT Single ManagedResource Notification Map. The first key is the digitalTwinId while the second key is
    // the resourceId and the value is the subResourceId
    private Map<String, Map<String, String>> managedResourceNotificationMap;

    // DT Augmentation Function Result Notification Map
    private Map<String, Map<String, List<List<AugmentationFunctionResult<?>>>>> augmentationFunctionResultNotificationMap;

    // Registration Augmentation Function Callbacks for each Handler
    private Map<String, Map<String, List<AugmentationFunction>>> augmentationFunctionRegistrationCallbackMap;

    // Registration Augmentation Function Callbacks for each Handler
    private Map<String, Map<String, List<AugmentationFunction>>> augmentationFunctionUnRegistrationCallbackMap;

    private SharedTestMetrics(){
        logger.info("SharedTestMetrics Constructor Called !");
        init();
    }

    public synchronized static SharedTestMetrics getInstance(){

        if(instance == null)
            instance = new SharedTestMetrics();

        return instance;
    }

    private void init(){
        logger.info("SharedTestMetrics -> Initializing ...");
        this.physicalAdapterPropertyEventMap = new HashMap<>();
        this.physicalAdapterEventNotificationMap = new HashMap<>();
        this.shadowingFunctionPropertyEventMap = new HashMap<>();
        this.shadowingFunctionEventNotificationMap = new HashMap<>();
        this.digitalAdapterEventNotificationMap = new HashMap<>();
        this.digitalAdapterStateUpdateMap = new HashMap<>();
        this.resourceManagerNotificationMap = new HashMap<>();
        this.managedResourceNotificationMap = new HashMap<>();
        this.augmentationFunctionResultNotificationMap = new HashMap<>();
        this.augmentationFunctionRegistrationCallbackMap = new HashMap<>();
        this.augmentationFunctionUnRegistrationCallbackMap = new HashMap<>();
    }

    public void registerDigitalTwin(String digitalTwinId){
        logger.info("SharedTestMetrics -> Registering DT with id: {}", digitalTwinId);
        this.physicalAdapterPropertyEventMap.put(digitalTwinId, new ArrayList<>());
        this.physicalAdapterEventNotificationMap.put(digitalTwinId, new ArrayList<>());
        this.shadowingFunctionPropertyEventMap.put(digitalTwinId, new ArrayList<>());
        this.shadowingFunctionEventNotificationMap.put(digitalTwinId, new ArrayList<>());
        this.digitalAdapterEventNotificationMap.put(digitalTwinId, new ArrayList<>());
        this.digitalAdapterStateUpdateMap.put(digitalTwinId, new ArrayList<>());
        this.resourceManagerNotificationMap.put(digitalTwinId, new ArrayList<>());
        this.managedResourceNotificationMap.put(digitalTwinId, new HashMap<>());
        this.augmentationFunctionResultNotificationMap.put(digitalTwinId, new HashMap<>());
        this.augmentationFunctionRegistrationCallbackMap.put(digitalTwinId, new HashMap<>());
        this.augmentationFunctionUnRegistrationCallbackMap.put(digitalTwinId, new HashMap<>());
    }

    public void unRegisterDigitalTwin(String digitalTwinId){
        logger.info("SharedTestMetrics -> UnRegistering DT with id: {}", digitalTwinId);
        this.physicalAdapterPropertyEventMap.remove(digitalTwinId);
        this.physicalAdapterEventNotificationMap.remove(digitalTwinId);
        this.shadowingFunctionPropertyEventMap.remove(digitalTwinId);
        this.shadowingFunctionEventNotificationMap.remove(digitalTwinId);
        this.digitalAdapterEventNotificationMap.remove(digitalTwinId);
        this.digitalAdapterStateUpdateMap.remove(digitalTwinId);
        this.resourceManagerNotificationMap.remove(digitalTwinId);
        this.managedResourceNotificationMap.remove(digitalTwinId);
        this.augmentationFunctionResultNotificationMap.remove(digitalTwinId);
        this.augmentationFunctionRegistrationCallbackMap.remove(digitalTwinId);
        this.augmentationFunctionUnRegistrationCallbackMap.remove(digitalTwinId);
    }

    public void resetMetrics(){

        logger.info("SharedTestMetrics -> Resetting ...");

        this.physicalAdapterPropertyEventMap.clear();
        this.physicalAdapterEventNotificationMap.clear();
        this.shadowingFunctionPropertyEventMap.clear();
        this.shadowingFunctionEventNotificationMap.clear();
        this.digitalAdapterEventNotificationMap.clear();
        this.digitalAdapterStateUpdateMap.clear();
        this.resourceManagerNotificationMap.clear();
        this.managedResourceNotificationMap.clear();
        this.augmentationFunctionResultNotificationMap.clear();
        this.augmentationFunctionRegistrationCallbackMap.clear();
        this.augmentationFunctionUnRegistrationCallbackMap.clear();

        init();
    }

    public void addPhysicalAdapterPropertyEvent(String digitalTwinId, PhysicalAssetPropertyWldtEvent<?> event){
        this.physicalAdapterPropertyEventMap.get(digitalTwinId).add(event);
    }

    public void addPhysicalAdapterEventNotification(String digitalTwinId, PhysicalAssetEventWldtEvent<?> event){
        this.physicalAdapterEventNotificationMap.get(digitalTwinId).add(event);
    }

    public void addShadowingFunctionPropertyEvent(String digitalTwinId, PhysicalAssetPropertyWldtEvent<?> event){
        this.shadowingFunctionPropertyEventMap.get(digitalTwinId).add(event);
    }

    public void addShadowingFunctionEventNotification(String digitalTwinId, PhysicalAssetEventWldtEvent<?> event){
        this.shadowingFunctionEventNotificationMap.get(digitalTwinId).add(event);
    }

    public void addDigitalAdapterEventNotification(String digitalTwinId, DigitalTwinStateEventNotification<?> event){
        this.digitalAdapterEventNotificationMap.get(digitalTwinId).add(event);
    }

    public void addDigitalAdapterStateUpdate(String digitalTwinId, DigitalTwinState digitalTwinState){
        this.digitalAdapterStateUpdateMap.get(digitalTwinId).add(digitalTwinState);
    }

    public void addResourceManagerNotification(String digitalTwinId, String resourceId){
        this.resourceManagerNotificationMap.get(digitalTwinId).add(resourceId);
    }

    public void addManagedResourceNotification(String digitalTwinId, String resourceId, String subResourceId){
        this.managedResourceNotificationMap.get(digitalTwinId).put(resourceId, subResourceId);
    }

    public void addAugmentationFunctionRegistrationCallback(String digitalTwinId,
                                                            String augmentationFunctionHandlerId,
                                                            AugmentationFunction augmentationFunction){
        // If the initial list of augmentation function registration callbacks for the specific augmentation function handler is not present, create a new one
        if(!this.augmentationFunctionRegistrationCallbackMap.get(digitalTwinId).containsKey(augmentationFunctionHandlerId)){
            this.augmentationFunctionRegistrationCallbackMap.get(digitalTwinId).put(augmentationFunctionHandlerId, new ArrayList<>());
        }

        // Save the augmentation function registration callback in the map
        this.augmentationFunctionRegistrationCallbackMap.get(digitalTwinId).get(augmentationFunctionHandlerId).add(augmentationFunction);
    }

    public void addAugmentationFunctionUnRegistrationCallback(String digitalTwinId,
                                                            String augmentationFunctionHandlerId,
                                                            AugmentationFunction augmentationFunction){
        // If the initial list of augmentation function unregistration callbacks for the specific augmentation function handler is not present, create a new one
        if(!this.augmentationFunctionUnRegistrationCallbackMap.get(digitalTwinId).containsKey(augmentationFunctionHandlerId)){
            this.augmentationFunctionUnRegistrationCallbackMap.get(digitalTwinId).put(augmentationFunctionHandlerId, new ArrayList<>());
        }

        // Save the augmentation function unregistration callback in the map
        this.augmentationFunctionUnRegistrationCallbackMap.get(digitalTwinId).get(augmentationFunctionHandlerId).add(augmentationFunction);
    }

    public void addAugmentationFunctionResultNotification(String digitalTwinId,
                                                          String augmentationFunctionHandlerId,
                                                          String augmentationFunctionId,
                                                          List<AugmentationFunctionResult<?>> augmentationFunctionResult){

        // Concatenate the augmentation function handler id and the augmentation function id to create a
        // unique key for the augmentation function result notification map
        String augmentationInternalId = String.format("%s.%s", augmentationFunctionHandlerId, augmentationFunctionId);

        // If the initial list of augmentation function results for the specific augmentation function is not present, create a new one
        if(!this.augmentationFunctionResultNotificationMap.get(digitalTwinId).containsKey(augmentationInternalId)){
            this.augmentationFunctionResultNotificationMap.get(digitalTwinId).put(augmentationInternalId, new ArrayList<>());
        }

        // Save the augmentation function result in the map
        this.augmentationFunctionResultNotificationMap.get(digitalTwinId).get(augmentationInternalId).add(augmentationFunctionResult);
    }

    public List<List<AugmentationFunctionResult<?>>> getAugmentationFunctionResultNotification(String digitalTwinId,
                                                                                         String augmentationFunctionHandlerId,
                                                                                         String augmentationFunctionId){

        // Concatenate the augmentation function handler id and the augmentation function id to create a
        // unique key for the augmentation function result notification map
        String augmentationInternalId = String.format("%s.%s", augmentationFunctionHandlerId, augmentationFunctionId);

        // Get the augmentation function result from the map
        return this.augmentationFunctionResultNotificationMap.get(digitalTwinId).get(augmentationInternalId);
    }

    public Map<String, List<PhysicalAssetPropertyWldtEvent<?>>> getPhysicalAdapterPropertyEventMap() {
        return physicalAdapterPropertyEventMap;
    }

    public Map<String, List<PhysicalAssetEventWldtEvent<?>>> getPhysicalAdapterEventNotificationMap() {
        return physicalAdapterEventNotificationMap;
    }

    public Map<String, List<PhysicalAssetPropertyWldtEvent<?>>> getShadowingFunctionPropertyEventMap() {
        return shadowingFunctionPropertyEventMap;
    }

    public Map<String, List<PhysicalAssetEventWldtEvent<?>>> getShadowingFunctionEventNotificationMap() {
        return shadowingFunctionEventNotificationMap;
    }

    public Map<String, List<DigitalTwinStateEventNotification<?>>> getDigitalAdapterEventNotificationMap() {
        return digitalAdapterEventNotificationMap;
    }

    public Map<String, List<DigitalTwinState>> getDigitalAdapterStateUpdateMap() {
        return digitalAdapterStateUpdateMap;
    }

    public Map<String, List<String>> getResourceManagerNotificationMap() {
        return resourceManagerNotificationMap;
    }

    public Map<String, Map<String, String>> getManagedResourceNotificationMap() {
        return managedResourceNotificationMap;
    }

    ////////

    public List<PhysicalAssetPropertyWldtEvent<?>> getPhysicalAdapterPropertyEventList(String digitalTwinId) {
        return physicalAdapterPropertyEventMap.get(digitalTwinId);
    }

    public List<PhysicalAssetEventWldtEvent<?>> getPhysicalAdapterEventNotificationList(String digitalTwinId) {
        return physicalAdapterEventNotificationMap.get(digitalTwinId);
    }

    public List<PhysicalAssetPropertyWldtEvent<?>> getShadowingFunctionPropertyEventList(String digitalTwinId) {
        return shadowingFunctionPropertyEventMap.get(digitalTwinId);
    }

    public List<PhysicalAssetEventWldtEvent<?>> getShadowingFunctionEventNotificationList(String digitalTwinId) {
        return shadowingFunctionEventNotificationMap.get(digitalTwinId);
    }

    public List<DigitalTwinStateEventNotification<?>> getDigitalAdapterEventNotificationList(String digitalTwinId) {
        return digitalAdapterEventNotificationMap.get(digitalTwinId);
    }

    public List<DigitalTwinState> getDigitalAdapterStateUpdateList(String digitalTwinId) {
        return digitalAdapterStateUpdateMap.get(digitalTwinId);
    }

    public Map<String, Map<String, List<List<AugmentationFunctionResult<?>>>>> getAugmentationFunctionResultNotificationMap() {
        return augmentationFunctionResultNotificationMap;
    }

    public Map<String, Map<String, List<AugmentationFunction>>> getAugmentationFunctionRegistrationCallbackMap() {
        return augmentationFunctionRegistrationCallbackMap;
    }

    public Map<String, Map<String, List<AugmentationFunction>>> getAugmentationFunctionUnRegistrationCallbackMap() {
        return augmentationFunctionUnRegistrationCallbackMap;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("SharedTestMetrics{");
        sb.append("physicalAdapterPropertyEventMap=").append(physicalAdapterPropertyEventMap);
        sb.append(", physicalAdapterEventNotificationMap=").append(physicalAdapterEventNotificationMap);
        sb.append(", shadowingFunctionPropertyEventMap=").append(shadowingFunctionPropertyEventMap);
        sb.append(", shadowingFunctionEventNotificationMap=").append(shadowingFunctionEventNotificationMap);
        sb.append(", digitalAdapterEventNotificationMap=").append(digitalAdapterEventNotificationMap);
        sb.append(", digitalAdapterStateUpdateMap=").append(digitalAdapterStateUpdateMap);
        sb.append(", resourceManagerNotificationMap=").append(resourceManagerNotificationMap);
        sb.append(", managedResourceNotificationMap=").append(managedResourceNotificationMap);
        sb.append('}');
        return sb.toString();
    }
}
