/*
 * Copyright (c) 2025 - Current Year
 * Marco Picone Ph.D
 * Email: picone.m@gmail.com
 * Website: https://www.marcopicone.net/
 * All rights reserved.
 *
 * This program is provided under a Dual Licensing model:
 * 1) GNU General Public License version 3.0 (GPL-3.0) for open-source, academic,
 *    research, non-profit, and other non-commercial use; or
 * 2) Commercial License, for any commercial use, proprietary development, or
 *    closed-source distribution. To obtain a Commercial License, please contact: Marco Picone (picone.m@gmail.com)
 *
 * By using this software, you agree to comply with the terms of the applicable license.
 * This applies to all forms of the software, including source code and compiled/binary forms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
package it.wldt.core.event.observer;

import it.wldt.core.event.*;
import it.wldt.exception.EventBusException;
import it.wldt.exception.WldtRuntimeException;
import it.wldt.log.WldtLogger;
import it.wldt.log.WldtLoggerProvider;

import java.util.Arrays;

/**
 * Author: Marco Picone (picone.m@gmail.com)
 * Date: 01/08/2024
 * Wldt Event Observer Class
 * This class is used to observe specific events generated by the Digital Twin Model and the Physical Adapters
 * Main mapped events and filters are:
 * - State Events: State Update and State Event Notifications
 * - Physical Asset Events: Physical Property Variation, Physical Event Notification, Physical Relationship Instance Creation and Deletion
 * - Physical Asset Action Events: Physical Action Trigger
 * - Digital Action Events: Digital Action Event
 * - Physical Asset Description Events: Physical Asset Description Available and Updated
 * - Life Cycle Events: Digital Twin Life Cycle Events
 * - Query Request Events: Storage Query Request Events
 */
public class WldtEventObserver implements WldtEventListener {

    private static final WldtLogger logger = WldtLoggerProvider.getLogger(WldtEventObserver.class);

    private WldtEventFilter dtStateEventFilter = null;

    private WldtEventFilter physicalAssetEventFilter = null;

    private WldtEventFilter physicalAssetActionEventFilter = null;

    private WldtEventFilter digitalActionEventFilter = null;

    private WldtEventFilter physicalAssetDescriptionEventFilter = null;

    private WldtEventFilter lifeCycleEventFilter = null;

    private WldtEventFilter queryRequestFilter = null;

    private WldtEventFilter queryResultFilter = null;

    private String observerId;

    private String digitalTwinId;

    private IWldtEventObserverListener observerListener;

    private WldtEventObserver() {
    }

    /**
     * Wldt Event Observer Constructor
     * @param digitalTwinId Digital Twin Id
     * @param observerId Observer Id
     * @param observerListener Observer Listener
     * @throws WldtRuntimeException Wldt Runtime Exception
     */
    public WldtEventObserver(String digitalTwinId, String observerId, IWldtEventObserverListener observerListener) throws WldtRuntimeException {

        this.digitalTwinId = digitalTwinId;
        this.observerId = observerId;

        if(digitalTwinId == null)
            throw new WldtRuntimeException("Observer digitalTwinId = Null in WldtEventObserver !");

        if(observerId == null)
            throw new WldtRuntimeException("Observer Id = Null in WldtEventObserver !");

        if(observerListener == null)
            throw new WldtRuntimeException("Observer Listener = Null in WldtEventObserver !");

        // Init Wldt Event Filters:
        this.dtStateEventFilter = new WldtEventFilter();
        this.physicalAssetEventFilter = new WldtEventFilter();
        this.physicalAssetActionEventFilter = new WldtEventFilter();
        this.digitalActionEventFilter = new WldtEventFilter();
        this.physicalAssetDescriptionEventFilter = new WldtEventFilter();
        this.lifeCycleEventFilter = new WldtEventFilter();
        this.queryRequestFilter = new WldtEventFilter();
        this.queryResultFilter = new WldtEventFilter();

        this.observerListener = observerListener;
    }

    /**
     * Trigger the observation of events generated from the Digital Twin Model related to State Variations and Event
     * Notifications
     * @param eventTypeList List of Event Types to Observe
     * @throws EventBusException Event Bus Exception
     */
    private void observeEventsWithFilter(WldtEventFilter targetFilter, String... eventTypeList){
        try{
            if(eventTypeList == null || eventTypeList.length == 0)
                logger.error("Error Observing Events ! Error: Empty/Null Filter or List ...");
            else {

                // If the filter has been already used cancel observation and clean the filter
                if(targetFilter != null)
                    unObserveEventsWithFilter(targetFilter);

                // Add target Event Types to the Filter
                if(targetFilter.addAll(Arrays.asList(eventTypeList)))
                    WldtEventBus.getInstance().subscribe(this.digitalTwinId, this.observerId, targetFilter, this);
                else
                    logger.error("Error Observing Events ! Impossible to add event to the Filter ...");
            }

        }catch (Exception e){
            logger.error("Error Observing Events ! Error: {}, EventTypeList: {}", e.getLocalizedMessage(), eventTypeList);
        }
    }

    /**
     * Cancel the observation of events generated from the Digital Twin Model related to State Variations and Event
     * Notifications
     * @param targetFilter Filter to Cancel
     * @throws EventBusException Event Bus Exception
     */
    public void unObserveEventsWithFilter(WldtEventFilter targetFilter) throws EventBusException {
        try{
            if (targetFilter != null && !targetFilter.isEmpty()) {
                WldtEventBus.getInstance().unSubscribe(this.digitalTwinId, this.observerId, targetFilter, this);
                targetFilter.clear();
                targetFilter = new WldtEventFilter();
            }
            //else
            //    logger.warn("Warning Canceling Observation Observing Events ! Empty/Null Filter or List ...");
        }catch (Exception e){
            logger.error("Error Canceling Observation for Events ! Error: {}, Filter: {}", e.getLocalizedMessage(), targetFilter);
        }
    }

    /**
     * Trigger the observation of events generated from the Digital Twin Model related to State Variations and Event
     * Notifications
     * @throws EventBusException
     */
    public void observeStateEvents() throws EventBusException {
        observeEventsWithFilter(this.dtStateEventFilter,
                WldtEventTypes.DT_STATE_UPDATE_MESSAGE_EVENT_TYPE,
                WldtEventTypes.ALL_DT_STATE_EVENT_NOTIFICATION_EVENT_TYPE);
    }

    /**
     * Cancel the observation of events generated from the Digital Twin Model related to State Variations and Event
     * Notifications
     * @throws EventBusException
     */
    public void unObserveStateEvents() throws EventBusException {
        unObserveEventsWithFilter(this.dtStateEventFilter);
    }


    /**
     * Trigger the observation of Physical Assets events generated from the active Physical Adapters
     * @throws EventBusException
     */
    public void observePhysicalAssetEvents() throws EventBusException {
        observeEventsWithFilter(this.physicalAssetEventFilter,
                WldtEventTypes.ALL_PHYSICAL_PROPERTY_VARIATION_EVENT_TYPE,
                WldtEventTypes.ALL_PHYSICAL_EVENT_NOTIFICATION_EVENT_TYPE,
                WldtEventTypes.ALL_PHYSICAL_RELATIONSHIP_INSTANCE_CREATION_EVENT_TYPE,
                WldtEventTypes.ALL_PHYSICAL_RELATIONSHIP_INSTANCE_DELETED_EVENT_TYPE);
    }

    /**
     * Cancel the observation of Physical Assets events generated from the active Physical Adapters
     * Notifications
     * @throws EventBusException
     */
    public void unObservePhysicalAssetEvents() throws EventBusException {
        unObserveEventsWithFilter(this.physicalAssetEventFilter);
    }

    /**
     * Trigger the observation of Physical Asset Action events generated from the Model for the Physical Adapters
     * @throws EventBusException
     */
    public void observePhysicalAssetActionEvents() throws EventBusException {
        observeEventsWithFilter(this.physicalAssetActionEventFilter,
                WldtEventTypes.ALL_PHYSICAL_ACTION_TRIGGER_EVENT_TYPE);
    }

    /**
     * Cancel the observation of Physical Asset Action events generated from the Model for the Physical Adapters
     * Notifications
     * @throws EventBusException
     */
    public void unObservePhysicalAssetActionEvents() throws EventBusException {
        unObserveEventsWithFilter(this.physicalAssetActionEventFilter);
    }

    /**
     * Trigger the observation of Digital Action events generated from Digital Adapter for the Model and the Shadowing
     * Function
     * @throws EventBusException
     */
    public void observeDigitalActionEvents() throws EventBusException {
        observeEventsWithFilter(this.digitalActionEventFilter,
                WldtEventTypes.ALL_DIGITAL_ACTION_EVENT_TYPE);
    }

    /**
     * Cancel the observation of Digital Action events generated from Digital Adapter for the Model and the Shadowing
     * Function
     * @throws EventBusException
     */
    public void unObserveDigitalActionEvents() throws EventBusException {
        unObserveEventsWithFilter(this.digitalActionEventFilter);
    }


    /**
     * Trigger the observation of Physical Asset Descriptions generated a Physical Assets
     * Function
     * @throws EventBusException
     */
    public void observePhysicalAssetDescriptionEvents() throws EventBusException {
        observeEventsWithFilter(this.physicalAssetDescriptionEventFilter,
                WldtEventTypes.PHYSICAL_ASSET_DESCRIPTION_AVAILABLE,
                WldtEventTypes.PHYSICAL_ASSET_DESCRIPTION_UPDATED);
    }

    /**
     * Cancel the observation of Physical Asset Descriptions generated a Physical Assets
     * @throws EventBusException
     */
    public void unObservePhysicalAssetDescriptionEvents() throws EventBusException {
        unObserveEventsWithFilter(this.physicalAssetDescriptionEventFilter);
    }

    /**
     * Trigger the observation of Life Cycle Events
     * Function
     * @throws EventBusException
     */
    public void observeLifeCycleEvents() throws EventBusException {
        observeEventsWithFilter(this.lifeCycleEventFilter,
                WldtEventTypes.DT_LIFE_CYCLE_EVENT_TYPE);
    }

    /**
     * Cancel the observation of Life Cycle Events
     * @throws EventBusException
     */
    public void unObserveLifeCycleEvents() throws EventBusException {
        unObserveEventsWithFilter(this.lifeCycleEventFilter);
    }

    /**
     * Trigger the observation of events associated to the Storage Query Requests
     * @throws EventBusException Event Bus Exception
     */
    public void observeStorageQueryRequestEvents() throws EventBusException {
        observeEventsWithFilter(this.queryRequestFilter,
                WldtEventTypes.STORAGE_QUERY_REQUEST_EVENT_TYPE);
    }

    /**
     * Cancel the observation of events associated to the Storage Query Requests
     * Notifications
     * @throws EventBusException
     */
    public void unObserveStorageQueryRequestEvents() throws EventBusException {
        unObserveEventsWithFilter(this.queryRequestFilter);
    }

    /**
     * Trigger the observation of events associated to the Storage Query Results
     * @throws EventBusException Event Bus Exception
     */
    public void observeStorageQueryResultEvents() throws EventBusException {
        observeEventsWithFilter(this.queryResultFilter,
                WldtEventTypes.ALL_STORAGE_QUERY_RESULT_EVENT_TYPE);
    }

    /**
     * Cancel the observation of events associated to the Storage Query Results
     * Notifications
     * @throws EventBusException
     */
    public void unObserveStorageQueryResultEvents() throws EventBusException {
        unObserveEventsWithFilter(this.queryResultFilter);
    }

    @Override
    public void onEventSubscribed(String eventType) {
        if(this.observerListener != null)
            this.observerListener.onEventSubscribed(eventType);
        else
            logger.error("WldtEventObserver({}) onEventSubscribed - Null Listener Error !", this.observerId);
    }

    @Override
    public void onEventUnSubscribed(String eventType) {
        if(this.observerListener != null)
            this.observerListener.onEventUnSubscribed(eventType);
        else
            logger.error("WldtEventObserver({}) onEventUnSubscribed - Null Listener Error !", this.observerId);
    }

    @Override
    public void onEvent(WldtEvent<?> wldtEvent) {

        if(this.observerListener == null)
            logger.error("WldtEventObserver({}) onEvent - Null Listener Error !", this.observerId);

        if(wldtEvent != null && wldtEvent.getType() != null){

            // Check State Events
            if(this.dtStateEventFilter != null && this.dtStateEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onStateEvent(wldtEvent);

            // Check Physical Asset Events
            if(this.physicalAssetEventFilter != null && this.physicalAssetEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onPhysicalAssetEvent(wldtEvent);

            // Check Physical Asset Action Events
            if(this.physicalAssetActionEventFilter != null && this.physicalAssetActionEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onPhysicalAssetActionEvent(wldtEvent);

            // Check Digital Action Events
            if(this.digitalActionEventFilter != null && this.digitalActionEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onDigitalActionEvent(wldtEvent);

            // Check Physical Asset Description Events
            if(this.physicalAssetDescriptionEventFilter != null && this.physicalAssetDescriptionEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onPhysicalAssetDescriptionEvent(wldtEvent);

            // Life Cycle Events
            if(this.lifeCycleEventFilter != null && this.lifeCycleEventFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onLifeCycleEvent(wldtEvent);

            // Check Query Request Events
            if(this.queryRequestFilter != null && this.queryRequestFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onQueryRequestEvent(wldtEvent);

            // Check Query Result Events
            if(this.queryResultFilter != null && this.queryResultFilter.matchEventType(wldtEvent.getType()))
                this.observerListener.onQueryResultEvent(wldtEvent);
        }
        else
            logger.error("WldtEventObserver({}) onEvent - Wrong or Null WldtEvent: {}", this.observerId, wldtEvent);
    }

    public WldtEventFilter getDtStateEventFilter() {
        return dtStateEventFilter;
    }

    public WldtEventFilter getPhysicalAssetEventFilter() {
        return physicalAssetEventFilter;
    }

    public WldtEventFilter getPhysicalAssetActionEventFilter() {
        return physicalAssetActionEventFilter;
    }

    public WldtEventFilter getDigitalActionEventFilter() {
        return digitalActionEventFilter;
    }

    public String getObserverId() {
        return observerId;
    }

    public String getDigitalTwinId() {
        return digitalTwinId;
    }

    public IWldtEventObserverListener getObserverListener() {
        return observerListener;
    }

    public void setDtStateEventFilter(WldtEventFilter dtStateEventFilter) {
        this.dtStateEventFilter = dtStateEventFilter;
    }

    public void setPhysicalAssetEventFilter(WldtEventFilter physicalAssetEventFilter) {
        this.physicalAssetEventFilter = physicalAssetEventFilter;
    }

    public void setPhysicalAssetActionEventFilter(WldtEventFilter physicalAssetActionEventFilter) {
        this.physicalAssetActionEventFilter = physicalAssetActionEventFilter;
    }

    public void setDigitalActionEventFilter(WldtEventFilter digitalActionEventFilter) {
        this.digitalActionEventFilter = digitalActionEventFilter;
    }

    public void setObserverId(String observerId) {
        this.observerId = observerId;
    }

    public void setDigitalTwinId(String digitalTwinId) {
        this.digitalTwinId = digitalTwinId;
    }

    public void setObserverListener(IWldtEventObserverListener observerListener) {
        this.observerListener = observerListener;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("WldtEventObserver{");
        sb.append("dtStateEventFilter=").append(dtStateEventFilter);
        sb.append(", physicalAssetEventFilter=").append(physicalAssetEventFilter);
        sb.append(", physicalAssetActionEventFilter=").append(physicalAssetActionEventFilter);
        sb.append(", digitalActionEventFilter=").append(digitalActionEventFilter);
        sb.append(", observerId='").append(observerId).append('\'');
        sb.append(", digitalTwinId='").append(digitalTwinId).append('\'');
        sb.append(", observerListener=").append(observerListener);
        sb.append('}');
        return sb.toString();
    }
}