/*
 * Copyright [2025] [Marco Picone, Ph.D. - picone.m@gmail.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Marco Picone <picone.m@gmail.com> - https://www.marcopicone.net/
 */
package it.wldt.adapter.physical;

import java.util.Map;

/**
 * Author:
 *          Marco Picone, Ph.D. (marco.picone@unimore.it)
 * Date: 20/06/2020
 * Structure of a Notification associated to an event generated by a Physical Asset
*/
public class PhysicalAssetEventNotification {

    // Timestamp of the event
    private long timestamp;

    // Event key associated to the event
    private String eventkey;

    // Body of the event
    private Object body;

    // Metadata associated to the event
    private Map<String, Object> metadata;

    /**
     * Default constructor
     */
    public PhysicalAssetEventNotification() {
    }

    /**
     * Constructor with all the required parameters
     * @param timestamp timestamp of the event
     * @param eventkey event key associated to the event
     * @param body body of the event
     * @param metadata  metadata associated to the event
     */
    public PhysicalAssetEventNotification(long timestamp, String eventkey, Object body, Map<String, Object> metadata) {
        this.timestamp = timestamp;
        this.eventkey = eventkey;
        this.body = body;
        this.metadata = metadata;
    }

    /**
     * Get the timestamp of the event
     * @return timestamp of the event
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Set the timestamp of the event
     * @param timestamp timestamp of the event
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Get the event key associated to the event
     * @return event key associated to the event
     */
    public String getEventkey() {
        return eventkey;
    }

    /**
     * Set the event key associated to the event
     * @param eventkey event key associated to the event
     */
    public void setEventkey(String eventkey) {
        this.eventkey = eventkey;
    }

    /**
     * Get the body of the event
     * @return body of the event
     */
    public Object getBody() {
        return body;
    }

    /**
     * Set the body of the event
     * @param body body of the event
     */
    public void setBody(Object body) {
        this.body = body;
    }

    /**
     * Get the metadata associated to the event
     * @return metadata associated to the event
     */
    public Map<String, Object> getMetadata() {
        return metadata;
    }

    /**
     * Set the metadata associated to the event
     * @param metadata metadata associated to the event
     */
    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("PhysicalAssetEventNotification{");
        sb.append("timestamp=").append(timestamp);
        sb.append(", eventkey='").append(eventkey).append('\'');
        sb.append(", body=").append(body);
        sb.append(", metadata=").append(metadata);
        sb.append('}');
        return sb.toString();
    }
}
