/*
 * Copyright (c) 2025 - Current Year
 * Marco Picone Ph.D
 * Email: picone.m@gmail.com
 * Website: https://www.marcopicone.net/
 * All rights reserved.
 *
 * This program is provided under a Dual Licensing model:
 * 1) GNU General Public License version 3.0 (GPL-3.0) for open-source, academic,
 *    research, non-profit, and other non-commercial use; or
 * 2) Commercial License, for any commercial use, proprietary development, or
 *    closed-source distribution. To obtain a Commercial License, please contact: Marco Picone (picone.m@gmail.com)
 *
 * By using this software, you agree to comply with the terms of the applicable license.
 * This applies to all forms of the software, including source code and compiled/binary forms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
package it.wldt.adapter.physical;

import java.util.Map;

/**
 * Author:
 *          Marco Picone, Ph.D. (marco.picone@unimore.it)
 * Date: 20/06/2020
 * Structure of a Notification associated to an event generated by a Physical Asset
*/
public class PhysicalAssetEventNotification {

    // Timestamp of the event
    private long timestamp;

    // Event key associated to the event
    private String eventkey;

    // Body of the event
    private Object body;

    // Metadata associated to the event
    private Map<String, Object> metadata;

    /**
     * Default constructor
     */
    public PhysicalAssetEventNotification() {
    }

    /**
     * Constructor with all the required parameters
     * @param timestamp timestamp of the event
     * @param eventkey event key associated to the event
     * @param body body of the event
     * @param metadata  metadata associated to the event
     */
    public PhysicalAssetEventNotification(long timestamp, String eventkey, Object body, Map<String, Object> metadata) {
        this.timestamp = timestamp;
        this.eventkey = eventkey;
        this.body = body;
        this.metadata = metadata;
    }

    /**
     * Get the timestamp of the event
     * @return timestamp of the event
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Set the timestamp of the event
     * @param timestamp timestamp of the event
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Get the event key associated to the event
     * @return event key associated to the event
     */
    public String getEventkey() {
        return eventkey;
    }

    /**
     * Set the event key associated to the event
     * @param eventkey event key associated to the event
     */
    public void setEventkey(String eventkey) {
        this.eventkey = eventkey;
    }

    /**
     * Get the body of the event
     * @return body of the event
     */
    public Object getBody() {
        return body;
    }

    /**
     * Set the body of the event
     * @param body body of the event
     */
    public void setBody(Object body) {
        this.body = body;
    }

    /**
     * Get the metadata associated to the event
     * @return metadata associated to the event
     */
    public Map<String, Object> getMetadata() {
        return metadata;
    }

    /**
     * Set the metadata associated to the event
     * @param metadata metadata associated to the event
     */
    public void setMetadata(Map<String, Object> metadata) {
        this.metadata = metadata;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("PhysicalAssetEventNotification{");
        sb.append("timestamp=").append(timestamp);
        sb.append(", eventkey='").append(eventkey).append('\'');
        sb.append(", body=").append(body);
        sb.append(", metadata=").append(metadata);
        sb.append('}');
        return sb.toString();
    }
}
